---
version: '3.7'

services:
  keycloak:
    image: jboss/keycloak:6.0.1
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=password
    - DB_ADDR=postgres
    - DB_PORT=5432
    - DB_DATABASE=keycloak
    - DB_SCHEMA=public
    - DB_USER=admin
    - DB_PASSWORD=password
    - DB_VENDOR=postgres
    depends_on:
    - postgres
    ports:
    - '8080:8080'
    - '8443:8443'
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=admin
    - POSTGRES_DB=keycloak
    ports:
    - '5432:5432'
